# Generated by Django 6.1.1 on 2026-10-06 05:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('en_revision', 'En revisión'), ('entrevista', 'Entrevista'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='enviada', max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='estudiantes.perfilestudiante')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='vacantes.vacante')),
            ],
            options={
                'verbose_name_plural': 'postulaciones',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'vacante'), name='postulacion_unica')],
            },
        ),
    ]
