# Generated by Django 6.1.1 on 2026-10-06 05:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('empresas', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Nombre del puesto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('requisitos', models.TextField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('hibrida', 'Híbrida'), ('remota', 'Remota')], max_length=20)),
                ('tipo', models.CharField(choices=[('practicas', 'Prácticas'), ('estadia', 'Estadía profesional'), ('medio_tiempo', 'Medio tiempo'), ('tiempo_completo', 'Tiempo completo'), ('egresados', 'Vacante para egresados')], max_length=20, verbose_name='Tipo de oportunidad')),
                ('experiencia', models.CharField(choices=[('ninguna', 'Sin experiencia'), ('menos_1', 'Menos de 1 año'), ('uno_dos', '1 a 2 años'), ('mas_2', 'Más de 2 años')], default='ninguna', max_length=20, verbose_name='Experiencia requerida')),
                ('ubicacion', models.CharField(max_length=120, verbose_name='Ubicación')),
                ('horario', models.CharField(blank=True, max_length=100)),
                ('salario', models.CharField(blank=True, help_text='Opcional. Ej.: $9,000 mensuales', max_length=100)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobada', 'Publicada'), ('rechazada', 'Rechazada'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20)),
                ('destacada', models.BooleanField(default=False)),
                ('carreras', models.ManyToManyField(blank=True, help_text='Déjalo vacío si la vacante es para cualquier carrera.', related_name='vacantes', to='catalogo.carrera')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='empresas.empresa')),
                ('habilidades', models.ManyToManyField(blank=True, related_name='vacantes', to='catalogo.habilidad')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='estudiantes.perfilestudiante')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='vacantes.vacante')),
            ],
            options={
                'ordering': ['-creado'],
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'vacante'), name='favorito_unico')],
            },
        ),
    ]
