# Generated by Django 6.1.1 on 2026-10-06 05:02

import django.core.validators
import django.db.models.deletion
import estudiantes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=120)),
                ('cuatrimestre', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.º cuatrimestre'), (2, '2.º cuatrimestre'), (3, '3.º cuatrimestre'), (4, '4.º cuatrimestre'), (5, '5.º cuatrimestre'), (6, '6.º cuatrimestre'), (7, '7.º cuatrimestre'), (8, '8.º cuatrimestre'), (9, '9.º cuatrimestre'), (10, '10.º cuatrimestre'), (11, '11.º cuatrimestre')], null=True)),
                ('es_egresado', models.BooleanField(default=False, verbose_name='Soy egresado')),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{7,20}$', 'Escribe un teléfono válido.')])),
                ('experiencia', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, upload_to=estudiantes.models.ruta_cv)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='catalogo.carrera')),
                ('habilidades', models.ManyToManyField(blank=True, related_name='estudiantes', to='catalogo.habilidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
